"""Replay an exported motion NPZ with the matching robot asset.

This script expects NPZ files generated by ``csv_to_npz_frog.py``.
It selects the robot asset from the ``robot_name`` field stored in the NPZ.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import torch

from isaaclab.app import AppLauncher

parser = argparse.ArgumentParser(description="Replay converted motions with the matching robot asset.")
parser.add_argument("--motion_file", type=str, required=True, help="Path to the motion npz file.")
AppLauncher.add_app_launcher_args(parser)
args_cli = parser.parse_args()

app_launcher = AppLauncher(args_cli)
simulation_app = app_launcher.app

import isaaclab.sim as sim_utils
from isaaclab.assets import Articulation, ArticulationCfg, AssetBaseCfg
from isaaclab.scene import InteractiveScene, InteractiveSceneCfg
from isaaclab.sim import SimulationContext
from isaaclab.utils import configclass
from isaaclab.utils.assets import ISAAC_NUCLEUS_DIR

from frog_lab.assets.g1_23dof import G1_23DOF_CFG
from frog_lab.assets.g1 import G1_CFG
from frog_lab.assets.g1_mimic import G1_CYLINDER_CFG
from frog_lab.tasks.mimic.mdp import MotionLoader


def _get_robot_asset_cfg(robot_name: str) -> ArticulationCfg:
    if robot_name == "g1":
        return G1_CYLINDER_CFG
    if robot_name == "g1_23":
        return G1_23DOF_CFG
    raise KeyError(f"Unknown robot_name '{robot_name}'. Supported: g1, g1_23")


def _load_motion_meta(motion_file: str) -> tuple[str, str, list[str], int]:
    data = np.load(motion_file, allow_pickle=True)
    try:
        robot_name = str(data["robot_name"][0]) if "robot_name" in data else "g1"
        root_link_name = str(data["root_link_name"][0]) if "root_link_name" in data else "pelvis"
        body_names = list(np.asarray(data["body_names"]).tolist())
        fps = int(np.asarray(data["fps"]).reshape(-1)[0]) if "fps" in data else 50
        return robot_name, root_link_name, body_names, fps
    finally:
        data.close()

def _build_scene_cfg(robot_cfg: ArticulationCfg) -> type[InteractiveSceneCfg]:
    @configclass
    class ReplayMotionSceneCfg(InteractiveSceneCfg):
        ground = AssetBaseCfg(prim_path="/World/defaultGroundPlane", spawn=sim_utils.GroundPlaneCfg())
        sky_light = AssetBaseCfg(
            prim_path="/World/skyLight",
            spawn=sim_utils.DomeLightCfg(
                intensity=750.0,
                texture_file=f"{ISAAC_NUCLEUS_DIR}/Materials/Textures/Skies/PolyHaven/kloofendal_43d_clear_puresky_4k.hdr",
            ),
        )
        robot: ArticulationCfg = robot_cfg.replace(prim_path="{ENV_REGEX_NS}/Robot")

    return ReplayMotionSceneCfg


def run_simulator(sim: SimulationContext, scene: InteractiveScene, motion: MotionLoader, root_link_name: str):
    robot: Articulation = scene["robot"]
    sim_dt = sim.get_physics_dt()

    if root_link_name not in motion.motion_body_names:
        raise ValueError(
            f"root_link_name '{root_link_name}' not found in motion bodies: {motion.motion_body_names}"
        )
    root_index = motion.motion_body_names.index(root_link_name)
    time_steps = torch.zeros(scene.num_envs, dtype=torch.long, device=sim.device)

    while simulation_app.is_running():
        time_steps += 1
        reset_ids = time_steps >= motion.time_step_total
        time_steps[reset_ids] = 0

        root_states = robot.data.default_root_state.clone()
        root_states[:, :3] = motion.body_pos_w[time_steps][:, root_index] + scene.env_origins[:, None, :]
        root_states[:, 3:7] = motion.body_quat_w[time_steps][:, root_index]
        root_states[:, 7:10] = motion.body_lin_vel_w[time_steps][:, root_index]
        root_states[:, 10:] = motion.body_ang_vel_w[time_steps][:, root_index]

        robot.write_root_state_to_sim(root_states)
        robot.write_joint_state_to_sim(motion.joint_pos[time_steps], motion.joint_vel[time_steps])
        scene.write_data_to_sim()
        sim.render()
        scene.update(sim_dt)

        pos_lookat = root_states[0, :3].cpu().numpy()
        sim.set_camera_view(pos_lookat + np.array([2.0, 2.0, 0.5]), pos_lookat)


def main():
    robot_name, root_link_name, body_names, motion_fps = _load_motion_meta(args_cli.motion_file)
    robot_cfg = _get_robot_asset_cfg(robot_name)

    sim_cfg = sim_utils.SimulationCfg(device=args_cli.device)
    sim_cfg.dt = 1.0 / float(motion_fps)
    sim = SimulationContext(sim_cfg)

    scene_cfg = _build_scene_cfg(robot_cfg)
    scene = InteractiveScene(scene_cfg(num_envs=1, env_spacing=2.0))

    sim.reset()
    motion = MotionLoader(args_cli.motion_file, body_names=body_names, device=sim.device)
    run_simulator(sim, scene, motion, root_link_name)


if __name__ == "__main__":
    main()
    simulation_app.close()
